In [4]:
import pandas as pd
from parse import parse

In [5]:
def bit_sum_32(b):
    b = ((b & 0xAAAAAAAA) >>  1) + (b & 0x55555555)
    b = ((b & 0xCCCCCCCC) >>  2) + (b & 0x33333333)
    b = ((b & 0xF0F0F0F0) >>  4) + (b & 0x0F0F0F0F)
    b = ((b & 0xFF00FF00) >>  8) + (b & 0x00FF00FF)
    b = ((b & 0xFFFF0000) >> 16) + (b & 0x0000FFFF)
    return b & 1

In [6]:
def add_parity(data):
    return (data << 1) | bit_sum_32(data)

In [7]:
def H3126_encode(data):
        return ((data & 0x3ffffff) << 5) \
             | (bit_sum_32(data & 0x3fff80) << 4) \
             | (bit_sum_32(data & 0x1c7f878) << 3) \
             | (bit_sum_32(data & 0x2d9e666) << 2) \
             | (bit_sum_32(data & 0x36ad555) << 1) \
             | bit_sum_32(data & 0x3b4b4cb)

In [8]:
def H3226_encode(data):
    return add_parity(H3126_encode(data))

In [9]:
def handleItemsList(s):
    arr = [0.] * 32
    if isinstance(s, str):
        vals = s.split(",")
        if vals:
            weight = 1. / len(vals)
            for v in vals:
                n = H3226_encode(int(parse("nm{}", v)[0]))
                for i in range(32):
                    arr[i] += weight if (n & (1 << i)) else 0.
    return tuple(arr)

In [18]:
def makeItemsDummies(col, df, prefix):
    temp = list(zip(*col.map(handleItemsList)))
    # return pd.DataFrame.from_records(temp)
    for i in range(32):
        df[prefix + str(i)] = temp[i]

In [48]:
!curl -O https://datasets.imdbws.com/title.crew.tsv.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 21 41.2M   21 9220k    0     0  8943k      0  0:00:04  0:00:01  0:00:03 8943k
 48 41.2M   48 19.9M    0     0   9.9M      0  0:00:04  0:00:02  0:00:02  9.9M
 64 41.2M   64 26.7M    0     0  9130k      0  0:00:04  0:00:03  0:00:01 9130k
 77 41.2M   77 31.8M    0     0  8124k      0  0:00:05  0:00:04  0:00:01 8124k
 97 41.2M   97 39.9M    0     0  8162k      0  0:00:05  0:00:05 --:--:-- 8162k
100 41.2M  100 41.2M    0     0  7827k      0  0:00:05  0:00:05 --:--:-- 7563k

In [11]:
crew = pd.read_csv("title.crew.tsv.gz" ,compression='gzip', sep='\t', dtype={"directors": str,"writers": str}, na_values = '\\N' )

In [15]:
makeItemsDummies(crew["directors"], crew, "d")

In [19]:
makeItemsDummies(crew["writers"], crew, "w")

In [20]:
crew.tail(10)

,tconst,directors,writers,d0,d1,d2,d3,d4,d5,d6,...,w22,w23,w24,w25,w26,w27,w28,w29,w30,w31
5977431,tt9916838,"nm5519454,nm5519375","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977432,tt9916840,nm0996406,"nm1482639,nm2586970",1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.5,1.000000,1.000000,0.0,0.500000,0.500000,0.000000,0.0,0.0,0.0
5977433,tt9916842,"nm5519454,nm5519375","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977434,tt9916844,"nm5519375,nm5519454","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977435,tt9916846,"nm5519454,nm5519375","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977436,tt9916848,"nm5519454,nm5519375","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977437,tt9916850,"nm5519375,nm5519454","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977438,tt9916852,"nm5519375,nm5519454","nm6182221,nm1628284,nm2921377",0.5,1.0,0.5,0.5,0.0,1.0,0.5,...,0.0,0.333333,0.666667,1.0,0.666667,0.333333,0.333333,0.0,0.0,0.0
5977439,tt9916856,nm10538645,nm6951431,0.0,0.0,1.0,0.0,1.0,1.0,1.0,...,0.0,1.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.0,0.0,0.0
5977440,tt9916880,nm0996406,"nm1482639,nm2586970",1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.5,1.000000,1.000000,0.0,0.500000,0.500000,0.000000,0.0,0.0,0.0

In [22]:
crew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5977441 entries, 0 to 5977440
Data columns (total 67 columns):
tconst       object
directors    object
writers      object
d0           float64
d1           float64
d2           float64
d3           float64
d4           float64
d5           float64
d6           float64
d7           float64
d8           float64
d9           float64
d10          float64
d11          float64
d12          float64
d13          float64
d14          float64
d15          float64
d16          float64
d17          float64
d18          float64
d19          float64
d20          float64
d21          float64
d22          float64
d23          float64
d24          float64
d25          float64
d26          float64
d27          float64
d28          float64
d29          float64
d30          float64
d31          float64
w0           float64
w1           float64
w2           float64
w3           float64
w4           float64
w5           float64
w6           float64
w7           float64
w8           float64
w9           float64
w10          float64
w11          float64
w12          float64
w13          float64
w14          float64
w15          float64
w16          float64
w17          float64
w18          float64
w19          float64
w20          float64
w21          float64
w22          float64
w23          float64
w24          float64
w25          float64
w26          float64
w27          float64
w28          float64
w29          float64
w30          float64
w31          float64
dtypes: float64(64), object(3)
memory usage: 3.0+ GB